description: Swarthmore College '28, studying CS and Film and Media Studies. Interested in applications of computing to games and digital media.

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

remote_theme: pages-themes/minimal@v0.2.0
title: Michelle Leonard
