description: Swarthmore '28<br> CS & Film and Media Studies <br> Interests: game studies, digital media

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

remote_theme: pages-themes/minimal@v0.2.0
title: Michelle Leonard
